name: link_dev
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management
  provider: ^6.0.1

  #ui
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.26
  cached_network_image: ^2.2.0+1
  shimmer:
    path: packages/flutter_shimmer

  #service
  dio: ^4.0.1

  #responsive
  flutter_screenutil: ^5.0.1

  #utils
  intl: ^0.17.0
  after_layout: ^1.1.0
  url_launcher: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/